### ISSUE TITLE
Error adding configMap

### ISSUE THREAD

**Issue by ju187** [kubernetes-sigs/application#104]
Tried to include configMap into the application and got an error 
error: unable to recognize "example.yaml": no matches for kind "ConfigMap" in version "apps/v1"

in the yaml it is defined like this
....
componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: ConfigMap
....
---
apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: cfgtcl
...

Please help.  Thanks.

**Comment by ant31** [comment]
ConfigMap is a 'core' resource

**Comment by janetkuo** [comment]
Like @ant31 mentioned, ConfigMap should be under `core` instead of `apps/v1`. Please reopen if this doesn't address your need. 

/close

**Comment by hemantha-kumara** [comment]
@janetkuo  I tried adding configmap 
```
componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: StatefulSet
    - group: core
      kind: ConfigMap

```
But in application status or logs, I dont see any information regarding configmap and service.
For more details on this issue pls refer to  https://github.com/kubernetes-sigs/application/issues/113
