### ISSUE TITLE
Cluster-scoped Application CRD

### ISSUE THREAD

**Issue by janetkuo** [kubernetes-sigs/application#111]
Application CRD doesn't work with cluster wide configurations, because it's namespace-scoped. 

We could create a `ClusterApplication` CRD, which can be an owner of both namespace-scoped and cluster-scoped resources.

**Comment by barney-s** [comment]
In addition to cluster scoped Application CRD, we can consider these as well:

1. Call then something more generic than application - say Stack ?
2. Allow different ways of grouping
  a. filtered addressing (dynamic) - labels + GK
  b. direct addressing  - GK/namespace/name OR GK/name OR uuid
  c. Nesting of application CRDs
3. Allow map[]{} field attachment.


```yaml

spec:
   attachment:
        istio:  
            key: value
       data-management:
            key: value
       slo:
           key: value
       ...
```
