### ISSUE TITLE
Referencing Secrets and other resources

### ISSUE THREAD

**Issue by konryd** [kubernetes-sigs/application#12]
This issue captures one of the threads on #4 where it was proposed to allow the Application to reference values/properties from Secret, ConfigMap, Ingress or Service.

Some quotes from the thread:
From @deustis: "[...]On the topic of credentials, we might want to establish a pattern for referencing Secrets. A very common getting started experience for an off-the-shelf app is trying to locate the password for an admin dashboard[...]"

@huyhg proposed simple templating system, where the template itself would live in spec and interpolated template would live in status.

@prydonius prefers enumerating reference types explicitly (Secret, ConfigMap, Ingress, Service)

@deustis proposed a templating system that would live in in spec but the evaluation would be the client responsibility (like @huyhg's proposal, but with no interpolation into spec). Also, the individual fields of the referenced objects would be selected using jsonpath.

@konryd pointed out that secret's values are typically evaluated on startup.

**Comment by konryd** [comment]
@deustis - to follow on my point - The assumption that applications support reloading of Secrets after editing is a big one. There's more info here (search for config maps):

https://github.com/kubernetes/kubernetes/issues/33664

**Comment by huyhg** [comment]
The discussions were specifically around information in `Value`s of the `Info` key-value pairs. The observation was that the values typically come from some common resources like Secret, ConfigMap, Ingress, or Service. We discussed various ways of how such references can be achieved and templatized.

**Comment by deustis** [comment]
Thanks @konryd for capturing the context from the thread. I'll just add a couple of the concrete proposals that were mentioned there:

In the model proposed by @prydonius where reference types are enumerated, this would be an example for a Secret reference:

```
- name: username
  value: user
- name: password
  valueFrom:
    secretKeyRef:
       name: wordpress-secret
       key: wordpress-password
```

Alternative, using more generalized resource references, this might look like:

```
- name: username
  value: user
- name: password
  valueFrom:
    kind: Secret
    name: wordpress-secret
    jsonPath: $.data.wordpress-password
    base64Decode: true
```

We might also consider supporting templatized values, which could either be evaluated by the UI or by a controller associated with the Application resource.

For example, to build an admin URL with dynamic IP and port assignments:

```
- name: Admin URL
  templateValue: http://{{ serviceIp }}:{{ servicePort }}/admin
  templateData:
    serviceRoot:
      valueFrom:
        kind: Service
        name: wordpress-external-service
        jsonPath: $.spec.clusterIP
    servicePort:
      valueFrom:
        kind: Service
        name: wordpress-external-service
        jsonPath: $.spec.ports[?(@.name==https)].port
```

**Comment by konryd** [comment]
From the [secret's docs](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets)

> Mounted Secrets are updated automatically
> 
> When a secret being already consumed in a volume is updated, projected keys are eventually updated as well. Kubelet is checking whether the mounted secret is fresh on every periodic sync. However, it is using its local ttl-based cache for getting the current value of the secret. As a result, the total delay from the moment when the secret is updated to the moment when new keys are projected to the pod can be as long as kubelet sync period + ttl of secrets cache in kubelet.

The secrets cache TTL is [one minute](https://github.com/kubernetes/kubernetes/blob/c6c03477cffc300e73e31395a3004a52d256e849/pkg/kubelet/secret/secret_manager.go#L38), and kubelet sync period is on the same order.

So the best sync that we can guarantee for Secrets alone is 2 minutes, after putting some restrictions on how they're set up (non-subpath volume mounts and not env vars).

**Comment by konryd** [comment]
I'd advocate for the solution proposed by @prydonius. The advantages are:
 * It covers all use cases.
 * It limits the use cases to 4 resource kinds, making it easier to optimize (fewer potential queries to fully render the Application).
 * It follows the conventions already present in K8s.
 * It avoids using jsonpath - a language with its own rich specification and &lt;Konrad speculating&gt;probably several incompatible implementations in various laguages&lt;/Konrad speculating&gt;

**Comment by ant31** [comment]
> We might also consider supporting templatized values,
I would not consider templating. 

References are aligned with current practice in the API, +1 on @prydonius proposal

**Comment by deustis** [comment]
I'm also onboard with @prydonius' proposal. In addition to the points @konryd mentioned above, it has the benefit of being extensible. Additional options can be added under valueFrom in the future:

```
- name: foo
  valueFrom:
    possibleExtensionHere:
```

**Comment by prydonius** [comment]
How do we see the Admin/App URL references looking like, as this will be different to referencing Secrets/ConfigMaps? My current thinking is to have a reference to either an Ingress or Service resource, along with an optional `path` for appending a path on the Ingress/Service host. For example:

```
links:
- description: App Home
  ingressRef:
    kind: Ingress
    name: wordpress-ingress
- description: Admin
  ingressRef:
    kind: Service
    name: wordpress-service
  path: /admin
```

This avoids the need for templating by assuming that links may only have a path appended to the URL, but does not take into account subdomains. It's also not clear to me how an Ingress with multiple hosts should be treated.
