### ISSUE TITLE
Onwers with Maintainers Structure

### ISSUE THREAD

**Issue by mattfarina** [kubernetes-sigs/application#16]
The structure for `maintainers` is:

```yaml
maintainers:
  - name: Kenneth Owens
    email: kow3ns@github.com
```

The structure for `owners` is:

```yaml
owners:
  - "Kenneth Owens kow3ns@github.com"
```

We should make these consistent. I didn't create a PR because I wasn't sure of the naming to use internally. I could use the `Maintainer` struct but the name isn't a great fit. Any ideas on the naming?
