### ISSUE TITLE
Add  printerColumns in the CRD spec

### ISSUE THREAD

**Issue by ant31** [kubernetes-sigs/application#163]
Add printerColumns in the CRD  for a better integration with Kubectl:

Suggestions about fields to display?
e.g: 
```
spec:
  additionalPrinterColumns:
  - name: Owner
    type: string
    description: The application object has an OwnerRef in matching resources
    JSONPath: .spec.addOwnerRef
  - name: Type
    type: string
    description:  The application type, e.g mariadb
    JSONPath: .spec.descriptor.type
  - name: Version
    type: string
    description: The Application version
    JSONPath: .spec.descriptor.version
```
output: 
```
$kubectl  get applications
NAME           OWNER   TYPE        VERSION
wordpress-01   true    wordpress   4.9.4
```
