### ISSUE TITLE
Wrong status for Services

### ISSUE THREAD

**Issue by rstefan1** [kubernetes-sigs/application#209]
I have this Service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ...
  namespace: ...
spec:
  clusterIP: [HIDDEN]
  externalTrafficPolicy: Local
  healthCheckNodePort: [HIDDEN]
  ports:
  - name: http
    nodePort: [HIDDEN]
    port: [HIDDEN]
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: [HIDDEN]
    port: [HIDDEN]
    protocol: TCP
    targetPort: https
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: [HIDDEN]
```

The type is `LoadBalancer`, `spec.clusterIP` is not empty,  `status.loadBalancer.ingress` is not empty and all objects in `status.loadBalancer.ingress` has an IP that is not empty.

I expect the status to be ready, but it is in progress.
