### ISSUE TITLE
[BUG] MatchExpressions is ignored on ApplicationSpec.Selector

### ISSUE THREAD

**Issue by bandesz** [kubernetes-sigs/application#216]
## What

I was trying to use MatchExpressions in ApplicationSpec.Selector but it wasn't working, e.g. my Application object did pick up all Deployment objects - including from other applications in the same namespace.

I have to use MatchExpressions, as the 3rd-party Helm chart I'm deploying tags all deployments with a different `app.kubernetes.io/name` label.

In my case I would need to use this:
```
selector:
  matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
        - calico-typha
        - calico-typha-autoscaler
```

Even if you don't want to support MatchExpressions, this is clearly a bug, as nothing stops you using it but it doesn't work as one would expect.

I think this project should support MatchExpressions, as although identifying an application with a single label is best practice, nothing guarantees that 3rd-party software do follow it.
