### ISSUE TITLE
CRD additionalPrinterColumns has a wrong description

### ISSUE THREAD

**Issue by eshiroma** [kubernetes-sigs/application#221]
In https://github.com/kubernetes-sigs/application/blob/master/config/crd/bases/app.k8s.io_applications.yaml there appears to be a copy-paste error:
```
    additionalPrinterColumns:
...
    - description: The creation date
      jsonPath: .spec.descriptor.version
      name: Version
```

Which should instead be:
```
    additionalPrinterColumns:
...
    - description: The version of the application
      jsonPath: .spec.descriptor.version
      name: Version
```

As a nit, `Numbers of components ready` is also probably better as `Number of components ready`.
