### ISSUE TITLE
Owner definition in Application CRD does not agree with README, not with sample/application.yaml

### ISSUE THREAD

**Issue by cvignola** [kubernetes-sigs/application#59]
Note README states type for maintainers and owners is the same: 

- spec.descriptor.maintainers | []ContactData 
- spec.descriptor.owners | []ContactData

However, in install.yaml they are dissimilar: 
```
                maintainers:
                  items:
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                      url:
                        type: string
                    type: object
                  type: array
```
and
```
                owners:
                  items:
                    type: string
                  type: array
                type:
                  type: string
```

Moreover, 

samples/application.yaml assumes maintainers and owners are the same type: 

```
    maintainers:
      - name: Kenneth Owens
        email: kow3ns@github.com
    owners:
      - name: Kenneth Owens
        email: kow3ns@github.com
```
Interestingly, samples/application.yaml successfully creates an application object on Kubernetes 1.8.0, 
but it fails on Kubernetes 1.9.1 with this error: 
_spec.descriptor.owners in body must be of type string: "object"_

I didn't try other versions.  But it's apparent the definition in install.yaml should be the same.  I fixed this in my local repo and would happily create a PR, but my company has not yet given me approval to sign the Contributor License Agreement (CLA) for this project.
