### ISSUE TITLE
Splitting application definition from instance selection

### ISSUE THREAD

**Issue by ecordell** [kubernetes-sigs/application#63]
The current application definition combines the description for a kind of an application with the selector for finding an instance of that kind of application.

We were thinking about how to use the application definition for [OLM](https://github.com/operator-framework/operator-lifecycle-manager), which has many of the same metadata needs as in the Application CRD. The fact that both metadata and selector are combined makes it hard to re-use for us.

For reference, here's the example application in the Readme:

```yaml
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "wordpress-01"
  labels:
    app.kubernetes.io/name: "wordpress-01"
    app.kubernetes.io/version: "3"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "wordpress-01"
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
  descriptor:
    version: "4.9.4"
    description: "WordPress is open source software you can use to create a beautiful website, blog, or app."
    icons:
      - src: "https://example.com/wordpress.png"
        type: "image/png"
    type: "wordpress"
    maintainers:
      - name: Kenneth Owens
        email: kow3ns@github.com
    owners:
      - "Kenneth Owens kow3ns@github.com"
    keywords:
      - "cms"
      - "blog"
      - "wordpress"
    links:
      - description: About
        url: "https://wordpress.org/"
      - description: Web Server Dashboard
        url: "https://metrics/internal/wordpress-01/web-app"
      - description: Mysql Dashboard
        url: "https://metrics/internal/wordpress-01/mysql"
```

I'd like to propose splitting this into two objects; one which represents the application kind, and one which selects a particular instance of that application.

For the example above, this would look like:

Description of Application Type: (note missing selector and name change)
```yaml
apiVersion: app.k8s.io/v1beta1
kind: ApplicationMetadata
metadata:
  name: "wordpress"
  labels:
    app.kubernetes.io/name: "wordpress"
    app.kubernetes.io/version: "3"
spec:
  version: "4.9.4"
  description: "WordPress is open source software you can use to create a beautiful website, blog, or app."
  icons:
  - src: "https://example.com/wordpress.png"
    type: "image/png"
  type: "wordpress"
  maintainers:
  - name: Kenneth Owens
    email: kow3ns@github.com
  owners:
  - "Kenneth Owens kow3ns@github.com"
  keywords:
  - "cms"
  - "blog"
  - "wordpress"
  links:
  - description: About
    url: "https://wordpress.org/"
  - description: Web Server Dashboard
    url: "https://metrics/internal/wordpress-01/web-app"
  - description: Mysql Dashboard
    url: "https://metrics/internal/wordpress-01/mysql"
```

and a selector for a specific instance of that application type:

```yaml
apiVersion: app.k8s.io/v1beta1
kind: ApplicationSelector
metadata:
  name: "wordpress-01"
  labels:
    app.kubernetes.io/metadata: "wordpress"
spec:
  metadata: "wordpress"
  selector:
    matchLabels:
     app.kubernetes.io/name: "wordpress-01"
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
status:
  assemblyPhase: "Pending"
```

I can then stamp out multiple instances (say, a `production` and a `staging`) without replicating all of the metadata between them.
