### ISSUE TITLE
To define ApplicationType as a new CRD

### ISSUE THREAD

**Issue by shaoxt** [kubernetes-sigs/application#70]
Looking into the Application definition, how do we manage common metadata for sample type of application. For example if we have a lot of "SpringBoot" applications, some of the metadata should be same, it will be duplicated in each same type of application and it will be hard to maintain.

**Comment by cmoulliard** [comment]
> Application definition

I agree with you that we need a field or a type to describe such info. This is the reason why I was also proposing in #68 to extend the Application CRD with Component CRD (and having a one to many relation) including such info

Example

```
apiVersion: component.k8s.io/v1alpha1
kind: Component
metadata:
  name: my-spring-boot
spec:
  deployment: innerloop
  packaging: jar
  type: application
  runtime: spring-boot          # Could be renamed to applicationType
  version: 1.5.15
  exposeService: true
```
