### ISSUE TITLE
matchLabels is insufficient for legacy uses. Can we support matchExpressions too?

### ISSUE THREAD

**Issue by ensonic** [kubernetes-sigs/application#73]
This syntax requires me to label all resources that belong to an app with the *same* label (both key and value). This might be hard for external pieces, that I don't want can't change easily.
```
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "wordpress-01"
```
Why can't we also support this:
```
spec:
  selector:
    matchExpressions:
      key: app
      operator: in
      values:  ["foo", "bar", "baz"]
```
