### ISSUE TITLE
ingressRef does not support HTTPS protocol

### ISSUE THREAD

**Issue by wgrzelak** [kubernetes-sigs/application#95]
Currently `ingressRef` supports only HTTP protocol. I would like to have there HTTPS protocol as well.

Current state:

```yaml
 - name: WordPress site address
    type: Reference
    valueFrom:
      ingressRef:
        name: $APP_INSTANCE_NAME-wordpress-ingress
```

Preferred state:

```yaml
 - name: WordPress site address
    type: Reference
    valueFrom:
      ingressRef:
        name: $APP_INSTANCE_NAME-wordpress-ingress
        protocol: HTTPS
```

I think the same needs could be with `serviceRef` as well.
